/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V4RouteImport } from './routes/v4'
import { Route as V3RouteImport } from './routes/v3'
import { Route as V2RouteImport } from './routes/v2'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ChurchesRouteImport } from './routes/churches'
import { Route as IndexRouteImport } from './routes/index'

const V4Route = V4RouteImport.update({
  id: '/v4',
  path: '/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const V3Route = V3RouteImport.update({
  id: '/v3',
  path: '/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchesRoute = ChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/churches': typeof ChurchesRoute
  '/events': typeof EventsRoute
  '/missions': typeof MissionsRoute
  '/v2': typeof V2Route
  '/v3': typeof V3Route
  '/v4': typeof V4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/churches': typeof ChurchesRoute
  '/events': typeof EventsRoute
  '/missions': typeof MissionsRoute
  '/v2': typeof V2Route
  '/v3': typeof V3Route
  '/v4': typeof V4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/churches': typeof ChurchesRoute
  '/events': typeof EventsRoute
  '/missions': typeof MissionsRoute
  '/v2': typeof V2Route
  '/v3': typeof V3Route
  '/v4': typeof V4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/churches' | '/events' | '/missions' | '/v2' | '/v3' | '/v4'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/churches' | '/events' | '/missions' | '/v2' | '/v3' | '/v4'
  id:
    | '__root__'
    | '/'
    | '/churches'
    | '/events'
    | '/missions'
    | '/v2'
    | '/v3'
    | '/v4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChurchesRoute: typeof ChurchesRoute
  EventsRoute: typeof EventsRoute
  MissionsRoute: typeof MissionsRoute
  V2Route: typeof V2Route
  V3Route: typeof V3Route
  V4Route: typeof V4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v4': {
      id: '/v4'
      path: '/v4'
      fullPath: '/v4'
      preLoaderRoute: typeof V4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3': {
      id: '/v3'
      path: '/v3'
      fullPath: '/v3'
      preLoaderRoute: typeof V3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churches': {
      id: '/churches'
      path: '/churches'
      fullPath: '/churches'
      preLoaderRoute: typeof ChurchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChurchesRoute: ChurchesRoute,
  EventsRoute: EventsRoute,
  MissionsRoute: MissionsRoute,
  V2Route: V2Route,
  V3Route: V3Route,
  V4Route: V4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
